<?php 
#################################################
#
#	FUNCTION parseForm
#	Takes the POSTed HB code and extracts the form,
#	parses out the HTML input elements, then pushes
# them into a hash: $hash = HTML name => HTML value 
#
#	RETURNS the hash of input name/value pairs
#
#################################################
function parseForm($hb_code) {
	$hb_form = substr(substr($_POST['hb_code'], 12), 0, -14);
	# pushing input elements into an array
	$dom = new DOMDocument;
	$dom->loadHTML($hb_form);
	foreach ($dom->getElementsByTagName('input') as $input_tag) {
    $form_inputs[] = trim(trim($dom->saveHTML($input_tag), '<input..>'));
	}

	# creating hash of name => value pairs
	foreach ($form_inputs as $input) {
		$name = explode('"', explode('name="', $input)[1])[0];
		$value = explode('"', explode('value="', $input)[1])[0];
		$hash[$name] = $value;
	}
	return $hash;
}

#################################################
#
#	FUNCTION createForm
# Takes the POSTed title for the form and the 
# HTML input name/value pairs generated by parseForm()
# and creates CSS-styled lines of HTML code for
# each relevant input field, then pushes them into
# a hash: $form_code = quick name of field => input value
#
#	RETURNS tha hash 
#
#################################################
function createForm($title, $button, $pairs) {
	$form_code['action'] = "<form action='https://app.hatchbuck.com/onlineForm/submit.php' method='POST'>";
	$form_code['title'] = "\t<span style='font-size:18px;font-family:sans-serif;'>$title</span>";

	foreach ($pairs as $name => $value) {
		if (substr($name, 3, 9) == 'firstName') {
			$form_code['fname'] = "\t<input style='min-width:80%;margin:3px;padding:5px;' id='pop-fname' name='$name' placeholder='First Name' />";
		} elseif (substr($name, 3, 8) == 'lastName') {
			$form_code['lname'] = "\t<input style='min-width:80%;margin:3px;padding:5px;' id='pop-lname' name='$name' placeholder='Last Name' />";
		} elseif (substr($name, 3, 5) == 'email') {
			$form_code['email'] = "\t<input style='min-width:80%;margin:3px;padding:5px;' id='pop-email' name='$name' placeholder='Email' />";
		} elseif (substr($name, 0, 6) == 'formID') {
			$form_code["form_id"] = "\t<input style='min-width:80%;margin:3px;padding:5px;' name='$name' value='$value' type='hidden' />";
		} elseif (substr($name, 0, 22) == 'enableServerValidation') {
			$form_code["server_validation"] = "\t<input style='min-width:80%;margin:3px;padding:5px;' name='$name' value='$value' type='hidden' />";
		} elseif (substr($name, 0, 17) == 'enable303Redirect') {
			$form_code["303_redirect"] = "\t<input style='min-width:80%;margin:3px;padding:5px;' name='$name' value='$value' type='hidden' />";
		} elseif (substr($name, 0, 7) == 'website') {
			$form_code["anti_spam"] = "\t<input style='min-width:80%;margin:3px;padding:5px;' name='$name' value='$value' type='hidden' />";
		} elseif (substr($name, 0, 10) == 'simple_spc') {
			$form_code["simple_spc"] = "\t<input style='min-width:80%;margin:3px;padding:5px;' name='$name' value='$value' type='hidden' />";
		}			
	}
	$form_code['submit'] = "\t<button style='min-width:80%;margin:3px;padding:5px;' id='pop-submit' type='submit'>$button</button>\n</form>";
	return $form_code;
}

#################################################
#
#	FUNCTION getWidget
#	Receives the prepared HB form code and wraps 
# it with the proper scripts and CSS to create
# the pop-up form on scroll
#
#	RETURNS the widget code
#
#################################################
function getWidget($form_code, $tracking_code) {
	$form = implode("\n", $form_code);
 $widget_code = "$tracking_code\n<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'></script>
<script type='text/javascript'>$(window).scroll(function(){if($(document).scrollTop()>=$(document).height()/5)$('#spopup').show('slow');else $('#spopup').hide('slow');});function closeSPopup(){\$('#spopup').hide('slow');}</script>
<div id='spopup' style='background:#fefefe;border-radius:4px;-moz-border-radius:4px;-webkit-border-radius:4px;-moz-box-shadow:inset 0 0 3px #333;-webkit-box-shadow:inset 0 0 3px #333;box-shadow:inner 0 0 3px #333;padding:12px 14px 12px 14px;width:300px;position:fixed;bottom:13px;right:2px;display:none;z-index:90;'>\n<a style='position:absolute;top:14px;right:10px;text-decoration: none;' href='javascript:void(0);' onclick='return closeSPopup();'><span style='font-size:12px;font-family:sans-serif; color:#aaa;'>close</span></a>\n$form\n</div>";
	return $widget_code;
}

#################################################
#
#	FUNCTION newPaste
# Loads an input form for new visitors to the page
#
#################################################
function newPaste() {
	return '
		<h1>Make sure to use the PLAIN HTML embed code!</h1>
		<form action="#" method="post">
			<table class="paste_input">
				<tr>
					<td>Webpage Tracking Code</td>
					<td><input name="tracking_code" placeholder="Paste webpage tracking code here" /></td>
				</tr>
				<tr>
					<td>Form Title</td>
					<td><input name="form_title" placeholder="Subscribe!" /></td>
				</tr>
				<tr>
					<td>Button Text</td>
					<td><input name="button_text" placeholder="Submit" /></td>
				</tr>
				<tr>
					<td>Hatchbuck Form Code</td>
				</tr>
			</table>
			<textarea name="hb_code" placeholder="Paste Hatchbuck code here"></textarea>
			<br /><br />
			<br />
			<button type="submit">Generate Code</button>
		</form>
	';
}
?>
